services:
  - type: web
    name: celular-app
    env: node
    buildCommand: npm install --prefix backend && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: cd backend && npm install && node index.js
    plan: free
